### ISSUE TITLE
Browser doesnt detect the cam

### ISSUE THREAD

**Issue by emdete** [Jugendhackt/Camera-Call-Chaos#1]
Hi, this is an incredible cool project - thank's for providing!

I found it working with `ffplay /dev/video2` (and had alot of fun) but none of my browser with any video page detects the cam. Do you have an idea, what's wrong?

**Comment by BC100Dev** [comment]
Hello. I'm sorry for the long wait since I just noticed that you created this issue.

What virtual camera do you use? The OBS virtual camera seems to work just fine on Linux. It might depend on the Linux kernel or the OS itself. Not fully 100% sure.

**Comment by emdete** [comment]
this really seem to depend on my notebook. using a different one works just fine. i wonder which cams are supported, which are not and why..
